/*
  Copyright 2006 by Sean Luke
  Licensed under the Academic Free License version 3.0
  See the file "LICENSE" for more information
 */

package thesis.evolution.nodes;

import thesis.evolution.DoubleData;
import ec.*;
import ec.gp.*;
import ec.util.*;

/**
 * A node representing if less than, else function in a program tree generated by genetic
 * programming.
 * 
 * @author Sean Luke
 * 
 */
public class Iflte extends GPNode {

	public String toString() {
		return "iflte";
	}
	
	public int expectedChildren() {
		return 4;
	}

	public void eval(final EvolutionState state, final int thread,
			final GPData input, final ADFStack stack,
			final GPIndividual individual, final Problem problem) {
		double condition1, condition2;
		DoubleData rd = ((DoubleData) (input));

		children[0].eval(state, thread, input, stack, individual, problem);
		condition1 = rd.x;
		children[1].eval(state, thread, input, stack, individual, problem);
		condition2 = rd.x;
		if (condition1 < condition2)
			children[2].eval(state, thread, input, stack, individual, problem);
		else
			children[3].eval(state, thread, input, stack, individual, problem);		
	}
}
